# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171024_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='next_nag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='nag_status_on',
            field=models.BooleanField(default=True),
        ),
    ]
