# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171102_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='often',
            field=models.BooleanField(default=False),
        ),
    ]
