# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_check_often'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='prev_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
