# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_check_prev_ping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='prev_ping',
        ),
    ]
